version: "3"

services:

  nginx:
    image: daocloud.io/library/nginx:1.16.1
    ports:
      - "80:80"
    privileged: true
    volumes:
      - "D:/docker/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "D:/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "D:/docker/nginx/log:/var/log/nginx"
      - "D:/docker/nginx/www:/var/www"
      - "D:/docker/nginx/etc/letsencrypt:/etc/letsencrypt"
    networks:
     default:
       ipv4_address: 172.18.0.5
    depends_on:
      - flask
    restart: always
    
    
  flask:
    image: daocloud.io/tchanbin/gzdhd:1.1
    ports:
      - "5000:5000"
    networks:
     default:
       ipv4_address: 172.18.0.4
    depends_on:
      - mysql
    restart: always
    
  mysql:
    image: daocloud.io/library/mysql:8.0.18
    command: --innodb-use-native-aio=0
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=11111111
    volumes:
      - "D:/docker/mysql/data:/var/lib/mysql"
    networks:
      default:
        ipv4_address: 172.18.0.3 
    restart: always
    
networks:
  default:
    external:
      name: mynet
