"""empty message

Revision ID: 0771ff50d694
Revises: bddb591943ce
Create Date: 2021-05-16 17:36:13.010652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0771ff50d694'
down_revision = 'bddb591943ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s4-data',
    sa.Column('openid', sa.String(length=60), nullable=False),
    sa.Column('gys_supplier', sa.String(length=50), nullable=True),
    sa.Column('gys_logisticsWeek', sa.String(length=50), nullable=True),
    sa.Column('gys_size', sa.Integer(), nullable=True),
    sa.Column('kh_totalMonth', sa.Integer(), nullable=True),
    sa.Column('kh_totalLeft', sa.Integer(), nullable=True),
    sa.Column('kh_totalRight', sa.Integer(), nullable=True),
    sa.Column('kh_huoPan', sa.Integer(), nullable=True),
    sa.Column('kh_banCi', sa.Integer(), nullable=True),
    sa.Column('cy_cycleTime', sa.Integer(), nullable=True),
    sa.Column('cy_SMEDTime', sa.Integer(), nullable=True),
    sa.Column('cy_upTime', sa.Integer(), nullable=True),
    sa.Column('cy_Operators', sa.Integer(), nullable=True),
    sa.Column('cy_EPE', sa.Integer(), nullable=True),
    sa.Column('cy_runningTime', sa.Integer(), nullable=True),
    sa.Column('cy_Wip', sa.Integer(), nullable=True),
    sa.Column('cy_valueTime', sa.Integer(), nullable=True),
    sa.Column('lsx_cycleTime', sa.Integer(), nullable=True),
    sa.Column('lsx_SMEDTime', sa.Integer(), nullable=True),
    sa.Column('lsx_upTime', sa.Integer(), nullable=True),
    sa.Column('lsx_Operators', sa.Integer(), nullable=True),
    sa.Column('lsx_Banci', sa.Integer(), nullable=True),
    sa.Column('lsx_runningTime', sa.Integer(), nullable=True),
    sa.Column('lsx_WipLeft', sa.Integer(), nullable=True),
    sa.Column('lsx_WipRight', sa.Integer(), nullable=True),
    sa.Column('lsx_valueTime', sa.Integer(), nullable=True),
    sa.Column('fy_WipLeft', sa.Integer(), nullable=True),
    sa.Column('fy_WipRight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('openid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s4-data')
    # ### end Alembic commands ###
