"""empty message

Revision ID: 503e11ce43d4
Revises: b51d0ad676d1
Create Date: 2021-04-16 15:25:19.424646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '503e11ce43d4'
down_revision = 'b51d0ad676d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s1-data', 'first_section')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s1-data', sa.Column('first_section', mysql.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
