"""empty message

Revision ID: 61716484556f
Revises: 27b1812bf6d8
Create Date: 2021-05-08 21:49:41.419757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61716484556f'
down_revision = '27b1812bf6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s1-data', sa.Column('gys_logisticsWeek', sa.String(length=50), nullable=True))
    op.add_column('s1-data', sa.Column('gys_size', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('gys_supplier', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s1-data', 'gys_supplier')
    op.drop_column('s1-data', 'gys_size')
    op.drop_column('s1-data', 'gys_logisticsWeek')
    # ### end Alembic commands ###
