"""empty message

Revision ID: e7683d7815df
Revises: 3c29a6a6b6f2
Create Date: 2021-04-28 20:19:22.258717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7683d7815df'
down_revision = '3c29a6a6b6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s1-data', sa.Column('hj_Banci', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('hj_Operators', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('hj_SMEDTime', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('hj_WipLeft', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('hj_WipRight', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('hj_cycleTime', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('hj_runningTime', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('hj_upTime', sa.Integer(), nullable=True))
    op.add_column('s1-data', sa.Column('hj_valueTime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s1-data', 'hj_valueTime')
    op.drop_column('s1-data', 'hj_upTime')
    op.drop_column('s1-data', 'hj_runningTime')
    op.drop_column('s1-data', 'hj_cycleTime')
    op.drop_column('s1-data', 'hj_WipRight')
    op.drop_column('s1-data', 'hj_WipLeft')
    op.drop_column('s1-data', 'hj_SMEDTime')
    op.drop_column('s1-data', 'hj_Operators')
    op.drop_column('s1-data', 'hj_Banci')
    # ### end Alembic commands ###
